// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCheckedIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLate")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("TotalHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Date")
                        .IsUnique();

                    b.ToTable("Attendances", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AttendanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal?>("SessionHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceId");

                    b.ToTable("AttendanceLogs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AttendanceRegularization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("HRorAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("HRorAdminId");

                    b.ToTable("AttendanceRegularizations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentName")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Designation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DesignationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DesignationName")
                        .IsUnique();

                    b.ToTable("Designations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("DesignationId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.LeaveBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<int>("RemainingLeaves")
                        .HasColumnType("int");

                    b.Property<int>("TotalLeaves")
                        .HasColumnType("int");

                    b.Property<int>("UsedLeaves")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("EmployeeId", "LeaveTypeId", "Year")
                        .IsUnique();

                    b.ToTable("LeaveBalances", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId1")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeId1");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveRequests", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DefaultDays")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PerformanceReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Goals")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewPeriod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Weaknesses")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("EmployeeId", "ReviewPeriod")
                        .IsUnique()
                        .HasDatabaseName("IX_PerformanceReviews_Employee_Period");

                    b.ToTable("PerformanceReviews", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Privilege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrivilegeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PrivilegeName")
                        .IsUnique();

                    b.ToTable("Privileges", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "View employee records",
                            PrivilegeName = "Employee.Read"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Create new employees",
                            PrivilegeName = "Employee.Create"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Update employee details",
                            PrivilegeName = "Employee.Update"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Delete employees",
                            PrivilegeName = "Employee.Delete"
                        },
                        new
                        {
                            Id = 5,
                            Description = "View departments",
                            PrivilegeName = "Department.Read"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Create departments",
                            PrivilegeName = "Department.Create"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Update departments",
                            PrivilegeName = "Department.Update"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Delete departments",
                            PrivilegeName = "Department.Delete"
                        },
                        new
                        {
                            Id = 9,
                            Description = "View designations",
                            PrivilegeName = "Designation.Read"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Create designations",
                            PrivilegeName = "Designation.Create"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Update designations",
                            PrivilegeName = "Designation.Update"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Delete designations",
                            PrivilegeName = "Designation.Delete"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Manage roles",
                            PrivilegeName = "Role.Manage"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Manage privileges",
                            PrivilegeName = "Privilege.Manage"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Assign roles to users",
                            PrivilegeName = "User.AssignRole"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Create new users",
                            PrivilegeName = "User.Create"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Read attendaces of employees",
                            PrivilegeName = "Attendance.Read"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Read report of attendaces",
                            PrivilegeName = "Attendance.ReadReport"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Update a attendace of employee",
                            PrivilegeName = "Attendance.Update"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Leave types getting and reading",
                            PrivilegeName = "Leave.Read"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Creating a leaves",
                            PrivilegeName = "Leave.Create"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Updating a existing leaves",
                            PrivilegeName = "Leave.Update"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Delete a leaves",
                            PrivilegeName = "Leave.Delete"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Updating a leave for Approve, Reject, Cancel",
                            PrivilegeName = "LeaveRequest.Update"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Generate a Employees salaries",
                            PrivilegeName = "Salary.Create"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Reading a employees salaries",
                            PrivilegeName = "Salary.Read"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Updating a employee salary",
                            PrivilegeName = "Salary.Update"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Create performance reviews for employees",
                            PrivilegeName = "Review.Create"
                        },
                        new
                        {
                            Id = 29,
                            Description = "View performance reviews and department summaries",
                            PrivilegeName = "Review.Read"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Update existing performance reviews",
                            PrivilegeName = "Review.Update"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Delete performance reviews",
                            PrivilegeName = "Review.Delete"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Send broadcast notifications to all employees",
                            PrivilegeName = "Notification.Broadcast"
                        },
                        new
                        {
                            Id = 33,
                            Description = "View the graphical analytics dashboard.",
                            PrivilegeName = "Dashboard.View"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Download the full CSV directory of employees.",
                            PrivilegeName = "Report.Employees"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Download monthly attendance CSV reports.",
                            PrivilegeName = "Report.Attendance"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Download monthly salary CSV reports.",
                            PrivilegeName = "Report.Salary"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Full system access",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Human Resources management",
                            RoleName = "HR"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Team and project management",
                            RoleName = "Manager"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Standard staff access",
                            RoleName = "Employee"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RolePrivilege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PrivilegeId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrivilegeId");

                    b.HasIndex("RoleId", "PrivilegeId")
                        .IsUnique();

                    b.ToTable("RolePrivileges", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 11,
                            PrivilegeId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            PrivilegeId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            PrivilegeId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            PrivilegeId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            PrivilegeId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 1,
                            PrivilegeId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            PrivilegeId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PrivilegeId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            PrivilegeId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            PrivilegeId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            PrivilegeId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            PrivilegeId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            PrivilegeId = 13,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            PrivilegeId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            PrivilegeId = 15,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 31,
                            PrivilegeId = 16,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 33,
                            PrivilegeId = 17,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 34,
                            PrivilegeId = 18,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 35,
                            PrivilegeId = 19,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 40,
                            PrivilegeId = 20,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 41,
                            PrivilegeId = 21,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 42,
                            PrivilegeId = 22,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 43,
                            PrivilegeId = 23,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 44,
                            PrivilegeId = 24,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 51,
                            PrivilegeId = 25,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 52,
                            PrivilegeId = 26,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 53,
                            PrivilegeId = 27,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 56,
                            PrivilegeId = 28,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 57,
                            PrivilegeId = 29,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 58,
                            PrivilegeId = 30,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 59,
                            PrivilegeId = 31,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 66,
                            PrivilegeId = 32,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 68,
                            PrivilegeId = 33,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 69,
                            PrivilegeId = 34,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 70,
                            PrivilegeId = 35,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 71,
                            PrivilegeId = 36,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 26,
                            PrivilegeId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 25,
                            PrivilegeId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 27,
                            PrivilegeId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 20,
                            PrivilegeId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 19,
                            PrivilegeId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 21,
                            PrivilegeId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 23,
                            PrivilegeId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 22,
                            PrivilegeId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 24,
                            PrivilegeId = 11,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 32,
                            PrivilegeId = 16,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 38,
                            PrivilegeId = 17,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 37,
                            PrivilegeId = 18,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 36,
                            PrivilegeId = 19,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 46,
                            PrivilegeId = 20,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 47,
                            PrivilegeId = 21,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 48,
                            PrivilegeId = 22,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 49,
                            PrivilegeId = 24,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 54,
                            PrivilegeId = 25,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 55,
                            PrivilegeId = 26,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 60,
                            PrivilegeId = 28,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 61,
                            PrivilegeId = 29,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 62,
                            PrivilegeId = 30,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 67,
                            PrivilegeId = 32,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 72,
                            PrivilegeId = 33,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 73,
                            PrivilegeId = 34,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 74,
                            PrivilegeId = 35,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 75,
                            PrivilegeId = 36,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 30,
                            PrivilegeId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 28,
                            PrivilegeId = 5,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 29,
                            PrivilegeId = 9,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 39,
                            PrivilegeId = 17,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 50,
                            PrivilegeId = 24,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 63,
                            PrivilegeId = 28,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 64,
                            PrivilegeId = 29,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 65,
                            PrivilegeId = 30,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.Salary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbsentDays")
                        .HasColumnType("int");

                    b.Property<decimal>("AnnualCTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Basic")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("DA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("EmployeePF")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EmployerPF")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GeneratedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Gratuity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossEarnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HRA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HalfDays")
                        .HasColumnType("int");

                    b.Property<decimal>("IncomeTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LopDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PaidLeaveDays")
                        .HasColumnType("int");

                    b.Property<string>("PayslipStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PresentDays")
                        .HasColumnType("int");

                    b.Property<decimal>("ProfessionalTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SpecialAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalWorkingDays")
                        .HasColumnType("int");

                    b.Property<decimal>("TravelAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnpaidLeaveDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Month", "Year")
                        .IsUnique()
                        .HasDatabaseName("IX_Salaries_Employee_Month_Year");

                    b.ToTable("Salaries", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SalaryStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CalculationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ComponentName")
                        .IsUnique();

                    b.ToTable("SalaryStructures", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Admin123@gmail.com",
                            IsActive = true,
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$wM2G6hTqj8oK9R1R1R1R1eO6S7j6K5L4M3N2O1P0Q9R8S7T6U5V",
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Attendance", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.AttendanceLog", b =>
                {
                    b.HasOne("Domain.Entities.Attendance", "Attendance")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("Domain.Entities.AttendanceRegularization", b =>
                {
                    b.HasOne("Domain.Entities.Attendance", "Attendance")
                        .WithMany()
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "HRorAdmin")
                        .WithMany()
                        .HasForeignKey("HRorAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Attendance");

                    b.Navigation("Employee");

                    b.Navigation("HRorAdmin");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.HasOne("Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Designation", "Designation")
                        .WithMany("Employees")
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Designation");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Domain.Entities.LeaveBalance", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.LeaveType", "LeaveType")
                        .WithMany("leaveBalances")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("Domain.Entities.LeaveRequest", b =>
                {
                    b.HasOne("Domain.Entities.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Employee", null)
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId1");

                    b.HasOne("Domain.Entities.LeaveType", "LeaveType")
                        .WithMany("leaveRequests")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("Notifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.PerformanceReview", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("PerformanceReviews")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Employee", "Reviewer")
                        .WithMany("ReviewsGiven")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Domain.Entities.RolePrivilege", b =>
                {
                    b.HasOne("Domain.Entities.Privilege", "Privilege")
                        .WithMany("RolePrivileges")
                        .HasForeignKey("PrivilegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("RolePrivileges")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Privilege");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Salary", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("Salaries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.User", "EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Attendance", b =>
                {
                    b.Navigation("AttendanceLogs");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Domain.Entities.Designation", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("LeaveRequests");

                    b.Navigation("Notifications");

                    b.Navigation("PerformanceReviews");

                    b.Navigation("ReviewsGiven");

                    b.Navigation("Salaries");

                    b.Navigation("Subordinates");
                });

            modelBuilder.Entity("Domain.Entities.LeaveType", b =>
                {
                    b.Navigation("leaveBalances");

                    b.Navigation("leaveRequests");
                });

            modelBuilder.Entity("Domain.Entities.Privilege", b =>
                {
                    b.Navigation("RolePrivileges");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePrivileges");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
